typography_spectrum: 0.16271862969733775
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.6904538236558437
  lightness: 0.7671449461486191
  saturation: 0.6451788439881057
  rhythmicContrast: 0.6643571141175926
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.72968
analytics:
  google: UA-77770177-1
  facebook: null
  twitter: null
name: The Green Gateway
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: The Green Gateway
description: 'Your Gateway to Green Energy News '
purpose: []
