typography_spectrum: 0.44074
color:
  brandColors:
    - '#1f54a4'
    - '#fdf8f4'
    - '#92bed7'
    - '#4b91c5'
    - '#203800'
  brandStrength: 0.375
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.72968
analytics:
  google: UA-77770177-1
  facebook: null
  twitter: null
name: The Green Gateway
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: The Green Gateway
description: 'Your Gateway to Green News '
purpose: []
