name: The Green Gateway
favicon: null
layout_spectrum: 0.762
typography_spectrum: 0.37022
title: The Green Gateway
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77770177-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f54a4'
    - '#fdf8f4'
    - '#92bed7'
    - '#4b91c5'
    - '#203800'
  brandStrength: 0.875
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
